### ISSUE TITLE
Define schemas as a resource

### ISSUE THREAD

**Issue by skaliy** [databricks/mlops-stacks#123]
How should we define schemas as a resource? I had  some difficulties with creating a schema.  Does DAB support schemas as a resource type?

```
resources:
  schemas:
    schema:
      name: my-mlops-project
      catalog_name: ${bundle.target}
      comment: Schema for the "example-project" ML Project for ${bundle.target} deployment target.
```
