### ISSUE TITLE
Compute cluster[Shared] for Service Principle to execute ML related workflows from GitHub Actions

### ISSUE THREAD

**Issue by puviarasu17** [databricks/mlops-stacks#140]
We are using the below cluster configuration in our template project created from mlops-stacks with Feature store and Unity Catalog options enabled. When we run, we are getting the below exception in feature-engineering-workflow-asset.yml when Feature store is trying to create table in Unity catalog. 

**Note:** We have the expected 'test' catalog in our metastore and the service principal has the right access. 

**Cluster Configuration in template project created from mlops-stacks:** 
```
new_cluster: &new_cluster
  new_cluster:
    num_workers: 1
    spark_version: 13.3.x-gpu-ml-scala2.12
    node_type_id: g2-standard-4
    custom_tags:
      clusterSource: mlops-stack
```

**Exception in GitHub actions:**
`ValueError: Catalog 'test' does not exist in the metastore.`

For an exploration of this issue, we tried the same notebook in an all-purpose cluster with shared access. We get the same exception. Also, we are getting the below exception when we try the sql query:` SELECT CURRENT_METASTORE()`;

**Exception in notebook attached to all-purpose shared cluster for the above sql:** 
`AnalysisException: [OPERATION_REQUIRES_UNITY_CATALOG] Operation CURRENT_METASTORE requires Unity Catalog enabled.`

Setting the spark config spark.databricks.unityCatalog.enabled to true is not working. 

Can you please suggest the correct compute config we should be using for mlops-stacks with unity catalog and feature store enabled?
