### ISSUE TITLE
Deploy pipeline fails with "staging: no such target. Available targets: ..."

### ISSUE THREAD

**Issue by ThomasHenckel** [databricks/mlops-stacks#186]
When using catalogue names that is not the default staging, test, prod this error will show

This is because the bundle sets the environment name in the databrick.yaml the same as the catalogue name
```
  {{ .input_staging_catalog_name }}:
    workspace:
      host: {{template `databricks_staging_workspace_host` .}}
```

Suggested fix
Keep the environment names staging, test, prod and set the catalog_name as a variable

```
  staging:
    variables:
      catalog_name: {{ .input_staging_catalog_name }}
    workspace:
      host: {{template `databricks_staging_workspace_host` .}}
```
In addition the bundle yml files in /resources have to be updated to use `${var. catalog_name}` where the variable is used to reference to the catalog name

I could pressend the fix as a PR if the fix sounds reasonable to you
